my_list = [1, '3', 0, 4, 1, True, None, [1, 2, 4]]
# print(my_list[0])
# print(my_list[-1])
# print(my_list[8])
# print(my_list[0:3:2])
# print(my_list[7:8])
# print(len(my_list))
# print(my_list[6][2])
# print(my_list[-3:])
# print(my_list[-1:-3])
# print(my_list[2::3])

# print(my_list.index('3'))
# my_list.append(56)
my_list.insert(2, "22")
my_list.remove('3')
# my_list.pop()
my_list.pop(2)
print(my_list)
